nacos:
  config:
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true
    group: DEFAULT_GROUP
    # 多个用逗号隔开，支持解析${}
    data-ids: yaml_config
    server-addr: "127.0.0.1:8848"
    ext-config:
      - type: properties
        auto-refresh: true
        group: DEFAULT_GROUP
        data-ids: prop_config
        server-addr: "127.0.0.1:8848"


# nacos配置是添加在environment最后的，application里的配置优先比他优先
pwd:
  info: i am applicaton.yml