nacos:
  config:
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true
    group: DEFAULT_GROUP
    # 多个用逗号隔开，支持解析${}
    data-ids: yaml_config
    server-addr: "127.0.0.1:8848"
    # 指定额外的配置（没指定的属性则会继承全局属性），支持指定其他nacos地址
    ext-config:
      - type: properties
        # 这个不声明的话是false，全局属性只支持固定的几个属性，并不包括auto-refresh【com.alibaba.boot.nacos.config.util.NacosConfigLoader.buildGlobalNacosProperties】
        auto-refresh: true
        group: DEFAULT_GROUP
        data-ids: prop_config
    username: nacos
    password: nacos


# nacos配置是添加在environment最后的，application里的配置优先比他优先
pwd:
  info: i am applicaton.yml


management:
  endpoints:
    web:
      exposure:
        include:
          - env