# 2.4以后官方说了禁止在非根配置文件下再激活其他配置文件，这会导致某些配置被覆盖

server:
  port: 81
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: dev,yml2,knife4j


---
# spring.config.activate.on-profile这个配置是结合三个短横线一起使用
# 标识这一段配置仅在指定环境生效时才加载，直至加载到下一个分隔符（三短横线）,等同于定义一个appliaction-yml2.yml
spring:
  config:
    activate:
      on-profile: yml2
controller:
  MyController:
    enabled: true
hello:
  prefix: 自定义场景启动器的前缀
  suffix: 自定义场景启动器的后缀

#配置actuator
management:
  endpoints:
    web:
      exposure:
        #暴露所有端口，作用相当于低版本的management.security.enabled=false
        include: '*'
#          - health
#          - beans
#          - mappings
#          - heapdump
#          - env
  endpoint:
    health:
      #使health端点显示详细信息，比如自定义的HealthIndicator
      show-details: always
#自定义actuator属性
info:
  myInfo:
    test: spring-boot-actuator


---
spring:
  config:
    activate:
      on-profile: knife4j
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: false
    username: blade
    password: blade
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: true
    enableHostText: http://localhost
    enableRequestCache: true
    enableFilterMultipartApis: true
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
    enableFooter: true
    enableFooterCustom: true
    enableDynamicParameter: true
    footerCustomContent: Copyright © 2022 SpringBlade All Rights Reserved