server:
  port: 80
  servlet:
    context-path: /
spring:
  profiles:
    active: dev,yml2

---
spring:
  profiles: yml2
pwd:
  my-config:
    #my-str或者myStr都可以 可以用${key}从环境变量、配置文件中读，也可以使用${random.int[1,100]}这种随机数占位符，但是#{spEL}无效
#    my-str: this is str!${os.name}#{os.name}#{12+1}${12+1}${pwd.my-config.map1.age}${random.uuid}
    integer: 12
    bool: false
    date: 2019/08/21
    map1:
      name: pw蛋
      age: 18
    map2: {name: pw蛋,age: 18}
    list1:
      - "双引号\n不会处理转义字符"
      - '单引号\n会处理转义字符'
      - 没有引号\n会处理转义字符
      - >
        通过>（字符后面要回车）换行
        换行被空格替换，最后会有个换行符
      - |
        通过|（字符后面要回车）换行
        会保留换行符，最后会有个换行符
      - 在字符串中
        （无论有没有用引号括起来）
        回车换行
        换行被空格替换
    #todo复合集合类型报错
#    list2: [one,two,abc]
    error-properties:
      include-exception: true
      path: /errors

hello:
  prefix: 自定义场景启动器的前缀
  suffix: 自定义场景启动器的后缀

#配置actuator
management:
  endpoints:
    web:
      exposure:
        #暴露所有端口，作用相当于低版本的management.security.enabled=false
        include: '*'
#          - health
#          - beans
#          - mappings
#          - heapdump
#          - env
  endpoint:
    health:
      #使health端点显示详细信息，比如自定义的HealthIndicator
      show-details: always
#自定义actuator属性
info:
  myInfo:
    test: spring-boot-actuator
