server:
  port: 80
  servlet:
    context-path: /


pwd:
  my-config:
    #my-str或者myStr都可以
    my-str: >
      this is str!
      sdf
    integer: 12
    bool: false
    date: 2019/08/21
    map1:
      name: pw蛋
      age: 18
    map2: {name: pw蛋,age: 18}
    list1:
      - "双引号\n不会处理转义字符"
      - '单引号\n会处理转义字符'
      - 没有引号\n会处理转义字符
      - >
        通过>（字符后面要回车）换行
        换行被空格替换，最后会有个换行符
      - |
        通过|（字符后面要回车）换行
        会保留换行符，最后会有个换行符
      - 在字符串中
        （无论有没有用引号括起来）
        回车换行
        换行被空格替换
    list2: [one,two] #todo复合集合类型报错

