spring:
  profiles:
    active: hello,knife4j
pwd:
  my-config:
    #my-str或者myStr都可以 可以用${key}从环境变量、配置文件中读，也可以使用${random.int[1,100]}这种随机数占位符，但是#{spEL}无效
    #    my-str: this is str!${os.name}#{os.name}#{12+1}${12+1}${pwd.my-config.map1.age}${random.uuid}
    integer: 12
    bool: false
    date: 2019/08/21
    map1:
      name: pw蛋 ${project.version} @maven.param@
      age: 18
    map2: {name: pw蛋,age: 18}
    list1:
      - "双引号\n不会处理转义字符"
      - '单引号\n会处理转义字符'
      - 没有引号\n会处理转义字符
      - >
        通过>（字符后面要回车）换行
        换行被空格替换，最后会有个换行符
      - |
        通过|（字符后面要回车）换行
        会保留换行符，最后会有个换行符
      - 在字符串中
        （无论有没有用引号括起来）
        回车换行
        换行被空格替换
    #todo复合集合类型报错
    #    list2: [one,two,abc]
    list3:
      - name: 预警信息
        id0: 这是id0
        ruleName: 规则名称
    error-properties:
      include-exception: true
      path: /myPath


---
spring:
  config:
    activate:
      on-profile: hello
hello:
  prefix: 自定义场景启动器的前缀
  suffix: 自定义场景启动器的后缀


---
spring:
  config:
    activate:
      on-profile: knife4j
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: false
    username: blade
    password: blade
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: true
    enableHostText: http://localhost
    enableRequestCache: true
    enableFilterMultipartApis: true
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
    enableFooter: true
    enableFooterCustom: true
    enableDynamicParameter: true
    footerCustomContent: Copyright © 2022 SpringBlade All Rights Reserved