server:
  port: 80
  servlet:
    context-path: /

# DataSource Config
spring:
  datasource:
#    schema: classpath:sql/mysql.sql
#    data: classpath:sql/mysql.sql
  flyway:
    baselineOnMigrate: true
    baseline-version: 1  # 默认是1，所以V1.0.0这种不会被执行
  profiles:
    active: mysql
  jackson:
    default-property-inclusion: non_empty
    date-format: "yyyy-MM-dd HH:mm:ss"

mybatis-plus:
#  type-enums-package: pwd.allen.enums #配置枚举 支持通配符 * 或者 ; 分割
  mapper-locations:
    - classpath*:/mapper/**/*.xml #默认是这个位置
#  configuration-properties:
#    myGlobal: pwd #设置全局属性方式一
  configuration: #设置mybatis属性
    map-underscore-to-camel-case: true
    variables:
      myGlobal: pwd  ##设置全局属性方式二

logging:
  level:
    pwd.allen: debug

knife4j:
  #启用
  enable: true


---
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  config:
    activate:
      on-profile: mysql
  flyway:
    locations: classpath:flyway/mysql/ # sql文件的位置，默认classpath:db/migration/

---
# oracle
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: 123456
  config:
    activate:
      on-profile: oracle
  flyway:
    locations: classpath:flyway/oracle/ # sql文件的位置，默认classpath:db/migration/